package edu.fullstackproject.team1.services

import edu.fullstackproject.team1.dtos.commands.CreateTripCommand
import edu.fullstackproject.team1.dtos.commands.UpdateTripCommand
import edu.fullstackproject.team1.mappers.TripMapper
import edu.fullstackproject.team1.models.Trip
import edu.fullstackproject.team1.repositories.CityRepository
import edu.fullstackproject.team1.repositories.TripRepository
import edu.fullstackproject.team1.repositories.UserRepository
import org.springframework.http.HttpStatus
import org.springframework.stereotype.Service
import org.springframework.transaction.annotation.Transactional
import org.springframework.web.server.ResponseStatusException

@Service
@Transactional
class TripService(
	private val tripRepository: TripRepository,
	private val userRepository: UserRepository,
	private val cityRepository: CityRepository,
	private val tripMapper: TripMapper,
) {
	fun createTrip(email: String, command: CreateTripCommand): Trip {
		val user = userRepository.findByEmail(email)
			?: throw ResponseStatusException(HttpStatus.NOT_FOUND, "User not found")
		val city = cityRepository.findByIdWithCountryAndState(command.cityId)
			?: throw ResponseStatusException(HttpStatus.NOT_FOUND, "City not found")

		val trip = tripMapper.toEntity(command, user = user, city = city)
		return tripRepository.save(trip)
	}

	fun getUserTrips(email: String): List<Trip> {
		val user = userRepository.findByEmail(email)
			?: throw ResponseStatusException(HttpStatus.NOT_FOUND, "User not found")
		return tripRepository.findByUserWithCityAndCountry(user)
	}

	fun deleteTrip(email: String, id: Long) {
		val trip = tripRepository
			.findById(id)
			.orElseThrow { ResponseStatusException(HttpStatus.NOT_FOUND, "Trip not found") }
		if (trip.user.email != email) {
			throw ResponseStatusException(HttpStatus.FORBIDDEN, "Not allowed to delete this trip")
		}
		tripRepository.delete(trip)
	}

	fun updateTrip(email: String, id: Long, command: UpdateTripCommand): Trip {
		val existingTrip = tripRepository
			.findById(id)
			.orElseThrow { ResponseStatusException(HttpStatus.NOT_FOUND, "Trip not found") }
		if (existingTrip.user.email != email) {
			throw ResponseStatusException(HttpStatus.FORBIDDEN, "Not allowed to delete this trip")
		}
		var updatedName = existingTrip.name
		var updatedCity = existingTrip.city
		val nameWasAutoGenerated = (existingTrip.name == existingTrip.city.name)
		if (command.name != null && command.name.isNotBlank()) {
			updatedName = command.name
		}
		if (command.cityId != null && command.cityId != existingTrip.city.id) {
			updatedCity = cityRepository.findById(command.cityId)
				.orElseThrow { ResponseStatusException(HttpStatus.NOT_FOUND, "City not found") }
			if (nameWasAutoGenerated && command.name == null) {
				updatedName = updatedCity.name
			}
		}

		val trip = existingTrip.copy(
			name = updatedName,
			city = updatedCity,
			startDate = command.startDate ?: existingTrip.startDate,
			finishDate = command.endDate ?: existingTrip.finishDate,
		)
		return tripRepository.save(trip)
	}
}
