CREATE TABLE trips (
  id SERIAL PRIMARY KEY,
  city_id BIGINT NOT NULL REFERENCES cities(id),
  user_id BIGINT NOT NULL REFERENCES users(id),
  name TEXT NOT NULL,
  start_date DATE NOT NULL,
  finish_date DATE NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

